### ISSUE TITLE
请问如何跳转到指定章节？

### ISSUE THREAD

**Issue by zyx134** [ysbing/flutter_read#2]
@override
  Future<void> addChapter(BookSource source, int chapterIndex) async {
    _chapterSourceList[chapterIndex] = source;
    print("222;${!isAttach.value},${!_isLoadCompleter}");
    if (!isAttach.value || !_isLoadCompleter) {
      return;
    }
    print(
        "333,${chapterIndex + 1 == currentProgress_.chapterIndex},${chapterIndex - 1 == currentProgress_.chapterIndex}");
    if (chapterIndex + 1 == currentProgress_.chapterIndex) {
      await addBeforeChapter(chapterIndex);
      refreshCallback?.call();
    } else if (chapterIndex - 1 == currentProgress_.chapterIndex) {
      await addAfterChapter(chapterIndex);
      refreshCallback?.call();
    }
    int? currentPageIndex = currentPageIndexCallback?.call();
    if (currentPageIndex != null) {
      disableLeft.value = currentPageIndex <= firstIndex;
      disableRight.value = currentPageIndex >= firstIndex + pageTotal() - 1;
    }
  }
这一段代码中，有加载上一章和下一章的逻辑，但是没有加载指定章节的逻辑，请问如何调整到指定章节呢

**Comment by ysbing** [comment]
这个是加载章节，加载后，调用startReadBook方法来跳转，方法传参设置ChapterData里的chapterIndex即可跳转到指定章节

**Comment by zyx134** [comment]
> 这个是加载章节，加载后，调用startReadBook方法来跳转，方法传参设置ChapterData里的chapterIndex即可跳转到指定章节

谢谢大佬，已解决

**Comment by zyx134** [comment]
感谢
